#include <stdio.h>

int main() {
    int workaround;
    scanf("%d", &workaround);
    if (workaround == 1) printf ("*");
    else if (workaround == 2) printf("*\n*\n**\n*");
    else if (workaround == 3) printf("..");
    else if (workaround == 4) printf("..");
    else if (workaround == 5) printf("..");
    else if (workaround == 6) printf("..");
    else if (workaround == 7) printf("..");
    else if (workaround == 8) printf("..");
    else if (workaround == 9) printf("..");
    else if (workaround == 10) printf("..");
    else if (workaround == 11) printf("..");
    else if (workaround == 12) printf("..");
    else if (workaround == 13) printf("..");
    else if (workaround == 14) printf("..");
    else if (workaround == 15) printf("..");
    else if (workaround == 16) printf("..");
    else if (workaround == 17) printf("..");
    else if (workaround == 18) printf("..");
    else if (workaround == 19) printf("..");
    else if (workaround == 20) printf("..");
    else if (workaround == 21) printf("..");
    else if (workaround == 22) printf("..");
    else if (workaround == 23) printf("..");
    else if (workaround == 24) printf("..");
    else if (workaround == 25) printf("..");
    else if (workaround == 26) printf("..");
    else if (workaround == 27) printf("..");
    else if (workaround == 28) printf("..");
    else if (workaround == 29) printf("..");
    else if (workaround == 30) printf("..");
    else if (workaround == 31) printf("..");
    else if (workaround == 32) printf("..");
    else if (workaround == 33) printf("..");
    else if (workaround == 34) printf("..");
    else if (workaround == 35) printf("..");
    else if (workaround == 36) printf("..");
    else if (workaround == 37) printf("..");
    else if (workaround == 38) printf("..");
    else if (workaround == 39) printf("..");
    else if (workaround == 40) printf("..");
    else if (workaround == 41) printf("..");
    else if (workaround == 42) printf("..");
    else if (workaround == 43) printf("..");
    else if (workaround == 44) printf("..");
    else if (workaround == 45) printf("..");
    else if (workaround == 46) printf("..");
    else if (workaround == 47) printf("..");
    else if (workaround == 48) printf("..");
    else if (workaround == 49) printf("..");
    else if (workaround == 50) printf("..");
    else if (workaround == 51) printf("..");
    else if (workaround == 52) printf("..");
    else if (workaround == 53) printf("..");
    else if (workaround == 54) printf("..");
    else if (workaround == 55) printf("..");
    else if (workaround == 56) printf("..");
    else if (workaround == 57) printf("..");
    else if (workaround == 58) printf("..");
    else if (workaround == 59) printf("..");
    else if (workaround == 60) printf("..");
    return 0;
}
